module.exports = (pageObjects, value) => {
  pageObjects.setValue('@yearBuild', value.yearBuildValue)
  pageObjects.click('@foundationType')
  pageObjects.click('@foundationValue')
  pageObjects.pause(500)
  pageObjects.click('@constractionType')
  pageObjects.click('@contractionValue')
  pageObjects.pause(500)
  pageObjects.click('@numbOfStories')
  pageObjects.click('@numStoriesValue')
  pageObjects.pause(500)
  pageObjects.click('@heatType')
  pageObjects.click('@heatValue')
  pageObjects.pause(500)
  pageObjects.click('@roofMaterial')
  pageObjects.click('@roofMaterialValue')
  pageObjects.pause(500)
  pageObjects.setValue('@roofImpYear', value.roofY)
  pageObjects.setValue('@sqrFootage', value.sqrF)
  pageObjects.pause(1000)
  pageObjects.setValue('@replcmtAmount', value.replcmtAmount)
    pageObjects.pause(1000)
  pageObjects.click('@floodZone')
  pageObjects.click('@fireHyrdrnt')
  pageObjects.pause(1000)
  pageObjects.click('@fireStation')
  pageObjects.click('@submit')
  pageObjects.waitForElementVisible('@firstName', 10000)
}
